import { AnimatePresence, motion } from 'motion/react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { type BountyType } from '@/generated/prisma/enums';
import { type HackathonModel } from '@/prisma/models/Hackathon';
import Sparkle from '@/svg/sparkle';

import { getListingIcon } from '@/features/listings/utils/getListingIcon';

import { Templates } from './Templates';
import { AutoGenerateDropdownType } from './Type';

const MIN_CHARACTERS = 120;

interface AutoGenerateFormProps {
  type: BountyType;
  setType: (type: BountyType) => void;
  onBack?: () => void;
  onSubmit: () => void;
  input: string;
  setInput: (input: string) => void;
  setHackathonSlug: (hackathon: string) => void;
  hackathonSlug: string;
  hackathons?: HackathonModel[];
}

export function AutoGenerateForm({
  type,
  setType,
  onBack: _onBack,
  onSubmit,
  input,
  setInput,
  setHackathonSlug,
  hackathonSlug,
  hackathons,
}: AutoGenerateFormProps) {
  const [_selectedTemplate, _setSelectedTemplate] = useState<string>('');
  const [showValidation, setShowValidation] = useState(false);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter') {
      if (e.metaKey || e.ctrlKey || e.shiftKey) {
        e.preventDefault();
        handleSubmit();
        return;
      }
    }
  };

  const handleSubmit = () => {
    setShowValidation(true);

    const trimmedInput = input.trim();
    if (!trimmedInput || trimmedInput.length < MIN_CHARACTERS) {
      return;
    }

    onSubmit();
  };

  const currentHackathon = hackathons?.find((h) => h.slug === hackathonSlug);

  const typeLabel =
    type === 'hackathon'
      ? currentHackathon?.name + ' Track'
      : type === 'bounty'
        ? 'Bounty Listing'
        : 'Project Listing';

  return (
    <div className="space-y-4 p-5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {getListingIcon(type, '!size-4')}
          <h2 className="font-serif text-xl font-semibold text-[#1d1815]">
            Generate your <span className="capitalize">{typeLabel}</span> with
            AI
          </h2>
        </div>
        <div>
          <AutoGenerateDropdownType
            type={type}
            setType={setType}
            setHackathonSlug={setHackathonSlug}
            hackathonSlug={hackathonSlug}
            hackathons={hackathons}
            input={input}
            setInput={setInput}
          />
        </div>
      </div>

      <div className="relative space-y-4">
        <Textarea
          placeholder="Briefly describe the scope of your task"
          value={input}
          onChange={(e) => {
            setInput(e.target.value);
            // Hide validation if input becomes empty
            if (e.target.value.length === 0) {
              setShowValidation(false);
            }
          }}
          onKeyDown={handleKeyDown}
          onBlur={() => {
            // Show validation on blur if there's content
            if (input.length > 0) {
              setShowValidation(true);
            }
          }}
          className="min-h-55 w-full resize-none rounded-none border-2 border-[#1d1815] bg-[#f4eee3] text-[#1d1815] placeholder:text-[#1d1815]/40 focus-visible:border-[#ce4a2b] focus-visible:ring-0"
        />
        <AnimatePresence>
          {input.length === 0 && (
            <motion.div
              initial={{ opacity: 0, y: 10, filter: 'blur(4px)' }}
              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              exit={{ opacity: 0, y: 10, filter: 'blur(4px)' }}
              transition={{ type: 'spring', bounce: 0, duration: 0.3 }}
              className="absolute bottom-2 left-3 w-max"
            >
              <Templates
                type={type}
                onSelectTemplate={({ prompt }) => setInput(prompt)}
              />
            </motion.div>
          )}
        </AnimatePresence>
        <AnimatePresence>
          {showValidation &&
            input.length > 0 &&
            (() => {
              const charsWithoutTrailingSpaces = input.trim().length;
              return charsWithoutTrailingSpaces < MIN_CHARACTERS;
            })() && (
              <motion.div
                initial={{ opacity: 0, y: 10, filter: 'blur(4px)' }}
                animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
                exit={{ opacity: 0, y: 10, filter: 'blur(4px)' }}
                transition={{ type: 'spring', bounce: 0, duration: 0.3 }}
                className="absolute bottom-[0.0625rem] left-2/4 w-[calc(100%-0.125rem)] -translate-x-2/4 border-2 border-[#1d1815] bg-[#f7e4bd] p-2 text-xs font-medium text-[#1d1815]"
              >
                <p>
                  Write at least {MIN_CHARACTERS - input.trim().length}{' '}
                  characters more
                </p>
              </motion.div>
            )}
        </AnimatePresence>
      </div>

      <div className="flex justify-end">
        <Button
          onClick={handleSubmit}
          disabled={
            !input ||
            input?.trim() === '' ||
            (showValidation && input.trim().length < MIN_CHARACTERS)
          }
          className="w-fit rounded-none border-2 border-[#1d1815] bg-[#e6a12b] font-bold text-[#1d1815] shadow-[3px_3px_0_#1d1815] transition-all hover:translate-x-[1px] hover:translate-y-[1px] hover:bg-[#e6a12b] hover:shadow-[1px_1px_0_#1d1815] disabled:opacity-50"
        >
          <Sparkle />
          Generate Listing
        </Button>
      </div>
    </div>
  );
}
