import { usePrivy } from '@privy-io/react-auth';
import { useQuery } from '@tanstack/react-query';
import { useSetAtom } from 'jotai';
import { Lock, Pencil, PencilLine, Plus, Users } from 'lucide-react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useRouter } from 'next/router';
import posthog from 'posthog-js';
import { type ReactNode, useEffect, useMemo, useState } from 'react';

import BiListUl from '@/components/icons/BiListUl';
import { type IconType } from '@/components/icons/helpers/GenIcon';
import MdList from '@/components/icons/MdList';
import MdOutlineChatBubbleOutline from '@/components/icons/MdOutlineChatBubbleOutline';
import RiUserSettingsLine from '@/components/icons/RiUserSettingsLine';
import { EntityNameModal } from '@/components/modals/EntityNameModal';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Tooltip } from '@/components/ui/tooltip';
import { JTTG } from '@/constants/Telegram';
import { SolanaWalletProvider } from '@/context/SolanaWallet';
import { useDisclosure } from '@/hooks/use-disclosure';
import { Default } from '@/layouts/Default';
import { Meta } from '@/layouts/Meta';
import { SponsorContentSkeleton } from '@/layouts/SponsorLayoutSkeleton';
import { useUser } from '@/store/user';
import Sparkle from '@/svg/sparkle';
import { cn } from '@/utils/cn';

import { isAutoGenerateOpenAtom } from '@/features/listing-builder/atoms';
import { isCreateListingAllowedQuery } from '@/features/listing-builder/queries/is-create-allowed';
import { FooterCompact } from '@/features/navbar/components/FooterCompact';
import { UserMenu } from '@/features/navbar/components/UserMenu';
import { NavItem } from '@/features/sponsor-dashboard/components/NavItems';
import { activeHackathonsQuery } from '@/features/sponsor-dashboard/queries/active-hackathons';

const ProListingsAnnouncement = dynamic(
  () =>
    import('@/features/announcements/components/ProListingsAnnouncement').then(
      (m) => m.ProListingsAnnouncement,
    ),
  { ssr: false },
);

const Login = dynamic(
  () => import('@/features/auth/components/Login').then((m) => m.Login),
  { ssr: false },
);

const AutoGenerateDialog = dynamic(
  () =>
    import('@/features/listing-builder/components/AutoGenerate/Dialog').then(
      (m) => m.AutoGenerateDialog,
    ),
  { ssr: false },
);

const CreateListingModal = dynamic(
  () =>
    import('@/features/sponsor-dashboard/components/CreateListingModal').then(
      (m) => m.CreateListingModal,
    ),
  { ssr: false },
);

const SponsorInfoModal = dynamic(
  () =>
    import('@/features/sponsor-dashboard/components/SponsorInfoModal').then(
      (m) => m.SponsorInfoModal,
    ),
  { ssr: false },
);

interface LinkItemProps {
  name: string;
  link?: string;
  icon: IconType;
  isExternal?: boolean;
  posthog?: string;
}

export function SponsorLayout({
  children,
  isCollapsible = false,
}: {
  children: ReactNode;
  isCollapsible?: boolean;
}) {
  const { user, isLoading: isUserLoading } = useUser();
  const { authenticated, ready } = usePrivy();
  const router = useRouter();
  const { isOpen, onOpen, onClose } = useDisclosure();
  const {
    isOpen: isSponsorInfoModalOpen,
    onOpen: onSponsorInfoModalOpen,
    onClose: onSponsorInfoModalClose,
  } = useDisclosure();

  const [isEntityModalOpen, setIsEntityModalOpen] = useState(false);
  const { query } = router;

  const setAutoGenerateOpen = useSetAtom(isAutoGenerateOpenAtom);

  const open = !!query.open;
  useEffect(() => {
    if (open) {
      setAutoGenerateOpen(true);
    }
  }, [open]);

  const { data: isCreateListingAllowed } = useQuery(
    isCreateListingAllowedQuery,
  );

  const handleEntityClose = () => {
    setIsEntityModalOpen(false);
  };

  useEffect(() => {
    const modalsToShow = async () => {
      if (
        user?.currentSponsorId &&
        (!user?.firstName ||
          !user?.lastName ||
          !user?.username ||
          !user?.telegram)
      ) {
        onSponsorInfoModalOpen();
      } else if (!user?.currentSponsor?.entityName && user?.role !== 'GOD') {
        setIsEntityModalOpen(true);
      } else {
        setIsEntityModalOpen(false);
      }
    };
    modalsToShow();
  }, [user]);

  useEffect(() => {
    if (
      !isUserLoading &&
      ready &&
      authenticated &&
      user &&
      !user?.currentSponsorId
    ) {
      router.push('/earn');
    }
  }, [user, authenticated, ready, isUserLoading]);

  const { data: hackathons } = useQuery({
    ...activeHackathonsQuery(),
    enabled: !!user,
  });

  const isHackathonRoute = useMemo(
    () => router.asPath.startsWith('/earn/dashboard/hackathon'),
    [router.asPath],
  );

  const isLocalProfileVisible = useMemo(() => {
    const sponsorChapterId = user?.currentSponsor?.chapter?.id;
    if (!sponsorChapterId) return false;
    if (user?.role === 'GOD') return true;
    const isCoreMember = user?.people?.type?.toUpperCase() === 'CORE';
    return isCoreMember && user?.people?.chapterId === sponsorChapterId;
  }, [
    user?.currentSponsor?.chapter?.id,
    user?.people?.chapterId,
    user?.people?.type,
    user?.role,
  ]);

  if (ready && !authenticated) {
    return <Login isOpen={true} onClose={() => {}} />;
  }

  const isLoading = !ready || (authenticated && isUserLoading);

  const LinkItems: Array<LinkItemProps> = isHackathonRoute
    ? [
        {
          name: 'All Tracks',
          link: `/hackathon`,
          icon: MdList,
        },
        {
          name: 'Get Help',
          link: JTTG,
          icon: MdOutlineChatBubbleOutline,
          posthog: 'get help_sponsor',
        },
      ]
    : [
        {
          name: 'My Listings',
          link: '/listings',
          icon: BiListUl,
        },
        {
          name: 'Team Settings',
          link: '/team-settings',
          icon: RiUserSettingsLine,
        },
        ...(isLocalProfileVisible
          ? [
              {
                name: 'Local Profiles',
                link: '/local-profiles',
                icon: Users,
              },
            ]
          : []),
        {
          name: 'Edit Profile',
          link: '/sponsor/edit',
          icon: Pencil,
        },
        {
          name: 'FAQ',
          link: '/faq',
          icon: MdOutlineChatBubbleOutline,
          posthog: 'faq_sponsor',
        },
      ];

  const showContent = isHackathonRoute
    ? user?.hackathonId || user?.role === 'GOD'
    : user?.currentSponsor?.id;

  const isAnyModalOpen = isOpen || isSponsorInfoModalOpen || isEntityModalOpen;

  const isCreateLocked =
    isCreateListingAllowed !== undefined &&
    isCreateListingAllowed === false &&
    user?.role !== 'GOD';

  return (
    <SolanaWalletProvider>
      <Default
        className="bg-[#F4EEE3]"
        hideFooter
        meta={
          <Meta
            title="Superteam Earn | Work to Earn in Crypto"
            description="Explore the latest bounties on Superteam Earn, offering opportunities in the crypto space across Design, Development, and Content."
            noIndex
          />
        }
      >
        <SponsorInfoModal
          onClose={onSponsorInfoModalClose}
          isOpen={isSponsorInfoModalOpen}
        />

        {/* {router.pathname === '/dashboard/listings' && (
          <SponsorAnnouncements isAnyModalOpen={isAnyModalOpen} />
        )} */}

        <ProListingsAnnouncement isAnyModalOpen={isAnyModalOpen} />

        <EntityNameModal
          isOpen={isEntityModalOpen}
          onClose={handleEntityClose}
        />

        <div className="flex min-h-[80vh] px-3 md:hidden">
          <p className="pt-20 text-center text-xl font-medium text-slate-500">
            The Sponsor Dashboard on Earn is not optimized for mobile yet.
            Please use a desktop to check out the Sponsor Dashboard
          </p>
        </div>
        <div className="hidden min-h-[max(100vh,1000px)] justify-start md:flex">
          {/* slim icon rail */}
          <aside
            className={cn(
              'z-10 flex w-[84px] max-w-[84px] min-w-[84px] flex-col items-center border-r border-[rgba(231,211,193,0.08)] bg-[#1D1815] py-5',
              isCollapsible ? 'fixed top-12 bottom-0 left-0' : 'static',
            )}
          >
            {/* nav icons */}
            <nav className="flex flex-col items-center gap-1.5">
              {LinkItems.map((link) => (
                <NavItem
                  onClick={() => {
                    if (link.posthog) posthog.capture(link.posthog);
                  }}
                  className="ph-no-capture"
                  key={link.name}
                  link={link.link}
                  icon={link.icon}
                >
                  {link.name}
                </NavItem>
              ))}
            </nav>

            {/* create */}
            <div className="mt-2.5">
              {!isHackathonRoute ? (
                <DropdownMenu>
                  <Tooltip
                    content="Creating a new listing has been temporarily locked for you since you have 5 listings which are 'In Review'. Please announce the winners for such listings to create new listings."
                    disabled={!isCreateLocked}
                    contentProps={{ side: 'right' }}
                  >
                    <DropdownMenuTrigger asChild>
                      <button
                        type="button"
                        aria-label="Create new listing"
                        className={cn(
                          'ph-no-capture grid size-[46px] place-items-center rounded-[14px] bg-[#CE4A2B] text-white transition-all duration-200 hover:bg-[#A6371C]',
                          'disabled:cursor-not-allowed disabled:opacity-50',
                        )}
                        disabled={isCreateLocked}
                      >
                        {isCreateLocked ? (
                          <Lock className="size-4" />
                        ) : (
                          <Plus className="size-5" />
                        )}
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent
                      className="min-w-[200px] font-medium text-slate-500"
                      align="start"
                      side="right"
                    >
                      <DropdownMenuItem
                        className="flex items-center justify-between"
                        onClick={() => {
                          posthog.capture('new generate with ai_sponsor');
                          setAutoGenerateOpen(true);
                        }}
                      >
                        <span className="flex items-center gap-2 text-sm">
                          <Sparkle className="h-4 w-4" />
                          Generate with AI
                        </span>
                        <span>
                          <span className="rounded-full bg-emerald-50 px-1.5 py-0.5 text-[0.65rem] text-emerald-600">
                            2m
                          </span>
                        </span>
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        className="flex items-center justify-between"
                        onClick={() => {
                          posthog.capture('new start from scratch_sponsor');
                          onOpen();
                        }}
                      >
                        <span className="flex items-center gap-2 text-sm">
                          <PencilLine className="h-4 w-4" />
                          Start from Scratch
                        </span>
                        <span>
                          <span className="rounded-full bg-indigo-50 px-1.5 py-0.5 text-[0.65rem] text-indigo-600">
                            10m
                          </span>
                        </span>
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </Tooltip>
                </DropdownMenu>
              ) : (
                <Link
                  href="/earn/dashboard/new/?type=hackathon"
                  aria-label="Create new track"
                  className="group relative grid size-[46px] place-items-center rounded-[14px] bg-[#CE4A2B] text-white transition-all duration-200 hover:bg-[#A6371C]"
                >
                  <Plus className="size-5" />
                  <span className="font-secondary pointer-events-none absolute left-full z-40 ml-3 origin-left scale-90 rounded-lg border border-[rgba(231,211,193,0.12)] bg-[#1D1815] px-2.5 py-1.5 text-[11px] font-semibold tracking-[0.04em] whitespace-nowrap text-[#FBF7EE] uppercase opacity-0 shadow-[0_8px_24px_-8px_rgba(0,0,0,0.6)] transition-all duration-150 group-hover:scale-100 group-hover:opacity-100">
                    Create new track
                  </span>
                </Link>
              )}
            </div>

            <div className="flex-1" />

            {/* profile */}
            <UserMenu variant="rail" />

            <CreateListingModal
              isOpen={isOpen}
              onClose={onClose}
              hackathons={hackathons}
            />
            <AutoGenerateDialog hackathons={hackathons} />
          </aside>

          {(showContent || isLoading) && (
            <div
              className={cn(
                'w-full flex-1 overflow-x-auto bg-[#F4EEE3] py-5 pr-8 pl-4',
                isCollapsible ? 'ml-[84px]' : 'ml-0',
              )}
            >
              {isLoading ? <SponsorContentSkeleton /> : children}
            </div>
          )}
        </div>
        <FooterCompact />
      </Default>
    </SolanaWalletProvider>
  );
}
